name: Nix Checks

on: ['pull_request']

permissions:
  contents: read

concurrency:
  group: nix-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Flake Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - uses: cachix/cachix-action@v14
        with:
          name: naxdy-foss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run Flake Checks
        run: |
          nix flake check -j auto --print-build-logs
